name: fooderlich
description: a social recipe app to keep track of new dishes, and share with friends.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-66.0.dev <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.4
  google_fonts: ^2.3.1
  provider: ^6.0.2
  flutter_colorpicker: ^1.0.3
  intl: ^0.17.0
  uuid: ^3.0.5
  smooth_page_indicator: ^1.0.0+2
  webview_flutter: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.4


flutter:


  uses-material-design: true


  assets:
    - assets/
    - assets/food_pics/
    - assets/magazine_pics/
    - assets/sample_data/
    - assets/profile_pics/
    - assets/fooderlich_assets/
